config: &config
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10

version: 2
updates:
- package-ecosystem: bundler
  <<: *config
  ignore:
    - dependency-name: jekyll
      versions:
        - 4.x
- package-ecosystem: npm
  <<: *config